using Awaken.TG.Utility;

namespace Awaken.TG.Main.Localization {
    // Window > Asset Management > Load LocTerms
    
    //  Reads the locterms defined in this file. Creates Localization table missing entries
    //  and removes entries that no longer exist in this file 
    public static class LocTerms {
        public const string ScenePrefix = "Scene/";
        public const char NonBreakingSpace = '\u00A0';
        
        public static string GetSceneName(Assets.SceneReference scene) {
            return $"{ScenePrefix}{scene?.Name}".Translate();
        }
        
        [UnityEngine.Scripting.Preserve]
        public static readonly string
            // --- Generic
            WorkInProgress = "Generic/WorkInProgress",
            Level = "Generic/Level",
            LevelWithNumber = "Generic/LevelWithNumber",
            Experience = "Generic/Experience",
            ExperienceShort = "Generic/XP",
            Proficiency = "Generic/Proficiency",
            TalentPoints = "Generic/TalentPoints",
            BaseStatPoints = "Generic/BaseStatPoints",
            AvailablePoints = "Generic/AvailablePoints",
            PointsAvailable = "Generic/PointsAvailable",
            Interact = "Generic/Interact",
            Enable = "Generic/Enable",
            Disable = "Generic/Disable",
            Play = "Generic/Play",
            Pause = "Generic/Pause",
            Talk = "Generic/Talk",
            Heal = "Generic/Heal",
            Mount = "Generic/Mount",
            Pet = "Generic/Pet",
            Search = "Generic/Search",
            Read = "Generic/Read",
            Mine = "Generic/Mine",
            Dig = "Generic/Dig",
            KillUnconscious = "Generic/KillUnconscious",
            Gather = "Generic/Gather",
            Fish = "Generic/Fish",
            Lumber = "Generic/Lumber",
            Look = "Generic/Look",
            Sketch = "Generic/Sketch",
            Pickup = "Generic/Pickup",
            PickupAll = "Generic/PickupAll",
            Steal = "Generic/Steal",
            Change = "Generic/Change",
            PlaceOnGround = "Generic/PlaceOnGround",
            PlaceOnGroundNotValidScene = "Generic/PlaceOnGroundNotValidScene",
            PlaceOnGroundBlockedObjects = "Generic/PlaceOnGroundBlockedObjects",
            PlaceOnGroundBlockedTerrain = "Generic/PlaceOnGroundBlockedTerrain",
            PlaceOnGroundBlockedLocations = "Generic/PlaceOnGroundBlockedLocations",
            PlaceOnGroundTooCloseToWater = "Generic/PlaceOnGroundTooCloseToWater",
            Blocked = "Generic/Blocked",
            ToolRequired = "Generic/ToolRequired",
            Mining = "Generic/Mining",
            Digging = "Generic/Digging",
            Gathering = "Generic/Gathering",
            Fishing = "Generic/Fishing",
            Lumbering = "Generic/Lumbering",
            Spyglassing = "Generic/Spyglassing",
            Sketching = "Generic/Sketching",
            HealthPerSecond = "Generic/HealthPerSecond",
            HealthCostPerSecond = "Generic/HealthCostPerSecond",
            HealthAbbreviation = "Generic/HealthAbbreviation",
            Health = "Generic/Health",
            MaxHealth = "Generic/MaxHealth",
            StaminaAbbreviation = "Generic/StaminaAbbreviation",
            StaminaPerSecond = "Generic/StaminaPerSecond",
            StaminaCostPerSecond = "Generic/StaminaCostPerSecond",
            Stamina = "Generic/Stamina",
            MaxStamina = "Generic/MaxStamina",
            StaminaRegen = "Generic/StaminaRegen",
            StaminaUsageMultiplier = "Generic/StaminaUsageMultiplier",
            StaminaAndManaUsage = "Generic/StaminaAndManaUsage",
            SprintCostMultiplier = "Generic/SprintCostMultiplier",
            AdditionalBlockDrain = "Generic/AdditionalBlockDrain",
            ManaAbbreviation = "Generic/ManaAbbreviation",
            ManaPerSecond = "Generic/ManaPerSecond",
            ManaCostPerSecond = "Generic/ManaCostPerSecond",
            Mana = "Generic/Mana",
            MaxMana = "Generic/MaxMana",
            ManaUsageMultiplier = "Generic/ManaUsageMultiplier",
            ManaRegen = "Generic/ManaRegen",
            ManaRegenPercentage = "Generic/ManaRegenPercentage",
            MovementSpeedMultiplier = "Generic/MovementSpeedMultiplier",
            WyrdSkillRestoreInfo = "Generic/WyrdSkillRestoreInfo",
            WyrdSkillDuration = "Generic/WyrdSkillDuration",
            WyrdWhispers = "Generic/WyrdWhispers",
            WyrdMemoryShards = "Generic/WyrdMemoryShards",
            ParryStaminaDamageMultiplier = "Generic/ParryStaminaDamageMultiplier",
            ParryWindowBonus = "Generic/ParryWindowBonus",
            BlockingStaminaDamageMultiplier = "Generic/BlockingStaminaDamageMultiplier",
            ArrowRetrievalChance = "Generic/ArrowRetrievalChance",
            BowSwayMultiplier = "Generic/BowSwayMultiplier",

            MinimumHeavyDamageAdd = "Generic/MinimumHeavyDamageAdd",
            MaximumHeavyDamageAdd = "Generic/MaximumHeavyDamageAdd",

            Aggro = "Generic/Aggro",
            Strength = "Generic/Strength",
            Intelligence = "Generic/Intelligence",
            BowStrength = "Generic/BowStrength",
            DualWieldStrength = "Generic/DualWieldStrength",
            OneHandedStrength = "Generic/OneHandedStrength",
            TwoHandedStrength = "Generic/TwoHandedStrength",
            UnarmedStrength = "Generic/UnarmedStrength",
            MagicStrength = "Generic/MagicStrength",
            HoldBlockCostReduction = "Generic/HoldBlockCostReduction",
            LightAttackCost = "Generic/LightAttackCost",
            HeavyAttackCost = "Generic/HeavyAttackCost",
            CombatDamage = "Generic/CombatDamage",
            BlockStaminaCostMultiplier = "Generic/BlockStaminaCostMultiplier",
            DamageValue = "Generic/DamageValue",
            ArmorPenetration = "Generic/ItemArmorPenetration",
            DamageIncreasePerCharge = "Generic/DamageIncreasePerCharge",
            IncomingDamage = "Generic/IncomingDamage",
            ForceModifier = "Generic/ForceModifier",
            ForceStumbleThreshold = "Generic/ForceStumbleThreshold",
            ForceRagdollThreshold = "Generic/ForceRagdollThreshold",
            Duration = "Generic/Duration",
            UntilEndOfFightDuration = "Generic/UntilEndOfFight",
            Yes = "Generic/Yes",
            No = "Generic/No",
            None = "Generic/None",
            You = "Generic/You",
            YouGot = "Generic/YouGot",
            YouLost = "Generic/YouLost",
            Cancel = "Generic/Cancel",
            Exit = "Generic/Exit",
            Open = "Generic/Open",
            Close = "Generic/Close",
            Accept = "Generic/Accept",
            All = "Generic/All",
            Give = "Generic/Give",
            Get = "Generic/Get",
            Divider = "Generic/Divider",
            ItemWithPossessedQuantity = "Generic/ItemWithPossessedQuantity",
            ItemWithQuantity = "Generic/ItemWithQuantity",
            ItemWithPositiveQuantityChange = "Generic/ItemWithPositiveQuantityChange",
            ItemWithNegativeQuantityChange = "Generic/ItemWithNegativeQuantityChange",
            Preview = "Generic/Preview",
            Buy = "Generic/Buy",
            Sell = "Generic/Sell",
            SellFromStash = "Generic/SellFromStash",
            BuyBack = "Generic/BuyBack",
            Unlock = "Generic/Unlock",
            Locked = "Generic/Locked",
            InStock = "Generic/InStock",
            Available = "Generic/Available",
            Equipped = "Generic/Equipped",
            Add = "Generic/Add",
            Subtract = "Generic/Subtract",
            Added = "Generic/Added",
            Removed = "Generic/Removed",
            Exchange = "Generic/Exchange",
            NewStatus = "Generic/NewStatus",
            LockedStat = "Generic/LockedStat",
            Create = "Generic/Create",
            TryToCreate = "Generic/TryToCreate",
            Cook = "Generic/Cook",
            Reroll = "Generic/Reroll",
            BaseHealth = "Generic/BaseHealth",
            BaseDamage = "Generic/BaseDamage",
            Select = "Generic/Select",
            Journal = "Generic/Journal",
            Use = "Generic/Use",
            UseSomething = "Generic/UseSomething",
            ItemWillBeUsed = "Generic/ItemWillBeUsed",
            Eat = "Generic/Eat",
            Wealth = "Generic/Wealth",
            Cobweb = "Generic/Cobweb",
            Cost = "Generic/Cost",
            Amount = "Generic/Amount",
            WealthDescription = "Currency/WealthDescription",
            CobwebDescription = "Currency/CobwebDescription",
            Corruption = "Generic/Corruption",
            Leave = "Generic/Leave",
            AtLeast = "Generic/AtLeast",
            UpTo = "Generic/UpTo",
            Rest = "Generic/Rest",
            Resting = "Generic/Resting",
            CurrentTime = "Generic/CurrentTime",
            IncomingHealing = "Generic/IncomingHealing",
            ConsumableHealingBonus = "Generic/ConsumableHealingBonus",
            PotionHealingBonus = "Generic/PotionHealingBonus",
            PotionNameSingleEffect = "Generic/PotionNameSingleEffect",
            PotionNameDoubleEffect = "Generic/PotionNameDoubleEffect",
            DishNameWithEffect = "Generic/DishNameWithEffect",
            Transfer = "Generic/Transfer",
            Empty = "Generic/Empty",
            Delete = "Generic/Delete",
            Override = "Generic/Override",
            Load = "Generic/Load",
            On = "Generic/On",
            Off = "Generic/Off",
            Confirm = "Generic/Confirm",
            Requires = "Generic/Requires",
            GameOver = "Generic/GameOver",
            Days = "Generic/Days",
            Hours = "Generic/Hours",
            Minutes = "Generic/Minutes",
            Seconds = "Generic/Seconds",
            DaysAbbreviation = "Generic/DaysAbbreviation",
            HoursAbbreviation = "Generic/HoursAbbreviation",
            MinutesAbbreviation = "Generic/MinutesAbbreviation",
            SecondsAbbreviation = "Generic/SecondsAbbreviation",
            KilogramAbbreviation = "Generic/KilogramAbbreviation",
            Unknown = "Generic/Unknown",
            Stealing = "Generic/Stealing",
            Bounty = "Generic/Bounty",
            UnforgivableCrime = "Generic/UnforgivableCrime",
            Rename = "Generic/Rename",
            Remove = "Generic/Remove",
            Profile = "Generic/Profile",
            QuestLog = "Generic/QuestLog",
            Default = "Generic/Default",
            Chance = "Generic/Chance",
            Congratulations = "Generic/Congratulations",
            Common = "Generic/Common",
            NoChanges = "Generic/NoChanges",
            Immune = "Generic/Immune",
            Resistant = "Generic/Resistant",
            Saturation = "Generic/Saturation",
            Pose = "Generic/Pose",
            Filter = "Generic/Filter",
            Random = "Generic/Random",
            MoveUp = "Generic/MoveUp",
            MoveDown = "Generic/MoveDown",

            PortalBlockedByCombat = "Interaction/PortalBlockedByCombat",
            
            // --- Operands
            Less = "Operator/Less",
            LessOrEqual = "Operator/LessOrEqual",
            Equal = "Operator/Equal",
            GreaterOrEqual = "Operator/GreaterOrEqual",
            Greater = "Operator/Greater",

            // --- Story Acts
            Prologue = "Acts/Prologue",
            ActHoS = "Acts/HoS",
            ActCuanacht = "Acts/Cuanacht",
            ActForlorn = "Acts/Forlorn",
            
            // --- Item properties
            Weight = "Item/Weight",
            Length = "Item/Length",
            WeightLevel = "Item/WeightLevel",
            Value = "Item/Value",
            Quality = "Item/Quality",
            Quantity = "Item/Quantity",
            ItemLevel = "Item/Level",
            ItemArmor = "Item/Armor",
            ItemBlock = "Item/Block",
            ItemBlockGain = "Item/BlockGain",
            ItemBlockAngle = "Item/BlockAngle",
            BlockDamageReductionPercent = "Item/BlockDamageReductionPercent",
            ItemForce = "Item/Force",
            ItemForceGain = "Item/ForceGain",
            ItemForceDamagePushMultiplier = "Item/ForceDamagePushMultiplier",
            ItemPoiseDamage = "Item/PoiseDamage",
            ItemPoiseDamageGain = "Item/PoiseDamageGain",
            ItemPoiseDamageHeavyAttackMultiplier = "Item/PoiseDamageHeavyAttackMultiplier",
            ItemPoiseDamagePushMultiplier = "Item/PoiseDamagePushMultiplier",
            CannotUseSkillsOfItem = "Item/CannotUseSkillsOfItem",

            // --- Armor weight
            WeightVeryLight = "Item/WeightVeryLight",
            WeightLight = "Item/WeightLight",
            WeightMedium = "Item/WeightMedium",
            WeightHeavy = "Item/WeightHeavy",
            WeightVeryHeavy = "Item/WeightVeryHeavy",
            WeightOverload = "Item/WeightOverload",

            // --- Qualities
            QGarbage = "Quality/Garbage",
            QTool = "Quality/Tool",
            QWeak = "Quality/Weak",
            QNormal = "Quality/Normal",
            QMagic = "Quality/Magic",
            QStory = "Quality/Story",
            QQuest = "Quality/Quest",

            // --- Proficiency stats
            OneHanded = "Proficiency/OneHanded",
            TwoHanded = "Proficiency/TwoHanded",
            Unarmed = "Proficiency/Unarmed",
            Shield = "Proficiency/Shield",
            Archery = "Proficiency/Archery",
            ProficiencyEvasion = "Proficiency/Evasion",
            Acrobatics = "Proficiency/Acrobatics",
            Athletics = "Proficiency/Athletics",
            LightArmor = "Proficiency/LightArmor",
            MediumArmor = "Proficiency/MediumArmor",
            HeavyArmor = "Proficiency/HeavyArmor",
            Magic = "Proficiency/Magic",
            Alchemy = "Proficiency/Alchemy",
            Cooking = "Proficiency/Cooking",
            Handcrafting = "Proficiency/Handcrafting",
            ProficiencyIncreased = "Generic/ProficiencyIncrease",
            Sneak = "Proficiency/Sneak",
            Theft = "Proficiency/Theft",
            Lying = "Proficiency/Lying",
            Persuasion = "Proficiency/Persuasion",
            Intimidation = "Proficiency/Intimidation",

            OneHandedDescription = "Proficiency/OneHandedDescription",
            TwoHandedDescription = "Proficiency/TwoHandedDescription",
            UnarmedDescription = "Proficiency/UnarmedDescription",
            ShieldDescription = "Proficiency/ShieldDescription",
            ArcheryDescription = "Proficiency/ArcheryDescription",
            EvasionDescription = "Proficiency/EvasionDescription",
            AcrobaticsDescription = "Proficiency/AcrobaticsDescription",
            AthleticsDescription = "Proficiency/AthleticsDescription",
            LightArmorDescription = "Proficiency/LightArmorDescription",
            MediumArmorDescription = "Proficiency/MediumArmorDescription",
            HeavyArmorDescription = "Proficiency/HeavyArmorDescription",
            MagicDescription = "Proficiency/MagicDescription",
            AlchemyDescription = "Proficiency/AlchemyDescription",
            CookingDescription = "Proficiency/CookingDescription",
            HandcraftingDescription = "Proficiency/HandcraftingDescription",
            SneakDescription = "Proficiency/SneakDescription",
            TheftDescription = "Proficiency/TheftDescription",
            LyingDescription = "Proficiency/LyingDescription",
            PersuasionDescription = "Proficiency/PersuasionDescription",
            IntimidationDescription = "Proficiency/IntimidationDescription",

            Complexity = "Proficiency/Theft/Complexity",

            // --- Base Hero Stats
            RPGStrength = "RPGStats/Strength",
            RPGDexterity = "RPGStats/Dexterity",
            RPGSpirituality = "RPGStats/Spirituality",
            RPGPerception = "RPGStats/Perception",
            RPGEndurance = "RPGStats/Endurance",
            RPGPracticality = "RPGStats/Practicality",

            RPGStrengthDescription = "RPGStats/StrengthDescription",
            RPGDexterityDescription = "RPGStats/DexterityDescription",
            RPGSpiritualityDescription = "RPGStats/SpiritualityDescription",
            RPGPerceptionDescription = "RPGStats/PerceptionDescription",
            RPGEnduranceDescription = "RPGStats/EnduranceDescription",
            RPGPracticalityDescription = "RPGStats/PracticalityDescription",

            // --- Stats

            Evasion = "Stats/Evasion",
            Armor = "Stats/Armor",
            Resistance = "Stats/Resistance",
            DamageAbbreviation = "Stats/DamageAbbreviation",
            MoveSpeed = "Stats/MoveSpeed",
            SprintSpeed = "Stats/SprintSpeed",
            CrouchSpeedMultiplier = "Stats/CrouchSpeedMultiplier",
            SwimSpeed = "Stats/SwimSpeed",
            BlockingMovementMultiplier = "Stats/BlockingMovementMultiplier",
            JumpHeight = "Stats/JumpHeight",
            DashSpeed = "Stats/DashSpeed",
            DashStamina = "Stats/DashStamina",
            DashCostMultiplier = "Stats/DashCostMultiplier",
            MaxDashOptimalCounter = "Stats/MaxDashOptimalCounter",
            DashRegenDurationMultiplier = "Stats/DashRegenDurationMultiplier",
            Encumbrance = "Stats/Encumbrance",
            EncumbranceLimit = "Stats/EncumbranceLimit",
            ArmorWeightMultiplier = "Stats/ArmorWeightMultiplier",
            FootstepsNoisiness = "Stats/FootstepsNoisiness",
            OxygenLevel = "Stats/OxygenLevel",
            OxygenUsage = "Stats/OxygenUsage",
            DamageNullifier = "Stats/DamageNullifier",
            FallDamageMultiplier = "Stats/FallDamageMultiplier",
            VisibilityMultiplier = "Stats/VisibilityMultiplier",
            NoiseMultiplier = "Stats/NoiseMultiplier",
            NoiseAndVisibilityMultiplier = "Stats/NoiseAndVisibilityMultiplier",
            CrouchNoiseMultiplier = "Stats/CrouchNoiseMultiplier",
            CrouchVisibilityMultiplier = "Stats/CrouchVisibilityMultiplier",
            LockpickDamageMultiplier = "Stats/LockpickDamageMultiplier",
            LockpickToleranceMultiplier = "Stats/LockpickToleranceMultiplier",
            LootChanceMultiplier = "Stats/LootChanceMultiplier",
            StatusResistance = "Stats/StatusResistance",
            LightAttackSpeed1H = "Stats/LightAttackSpeed1H",
            HeavyAttackSpeed1H = "Stats/HeavyAttackSpeed1H",
            LightAttackSpeed2H = "Stats/LightAttackSpeed2H",
            HeavyAttackSpeed2H = "Stats/HeavyAttackSpeed2H",
            LightAttackSpeedDual = "Stats/LightAttackSpeedDual",
            HeavyAttackSpeedDual = "Stats/HeavyAttackSpeedDual",
            AttackSpeed = "Stats/AttackSpeed",
            BowDrawSpeed = "Stats/BowDrawSpeed",
            BowDrawSpeedMultiplier = "Stats/BowDrawSpeedMultiplier",
            BlockPrepareSpeed = "Stats/BlockPrepareSpeed",
            FistLightAttackSpeed = "Stats/FistLightAttackSpeed",
            FistHeavyAttackSpeed = "Stats/FistHeavyAttackSpeed",
            SpellChargeSpeed = "Stats/SpellChargeSpeed",
            DeflectPrecision = "Stats/DeflectPrecision",
            TrapDamageMultiplier = "Stats/TrapDamageMultiplier",
            MeleeDamageMultiplier = "Stats/MeleeDamageMultiplier",
            OneHandedMeleeDamageMultiplier = "Stats/OneHandedMeleeDamageMultiplier",
            TwoHandedMeleeDamageMultiplier = "Stats/TwoHandedMeleeDamageMultiplier",
            UnarmedMeleeDamageMultiplier = "Stats/UnarmedMeleeDamageMultiplier",
            RangedDamageMultiplier = "Stats/RangedDamageMultiplier",
            CriticalChance = "Stats/CriticalChance",
            CriticalDamageMultiplier = "Stats/CriticalDamageMultiplier",
            SneakDamageMultiplier = "Stats/SneakDamageMultiplier",
            BackStabDamageMultiplier = "Stats/BackStabDamageMultiplier",
            MeleeSneakDamageMultiplier = "Stats/MeleeSneakDamageMultiplier",
            WeakSpotDamageMultiplier = "Stats/WeakSpotDamageMultiplier",
            MeleeCriticalChance = "Stats/MeleeCriticalChance",
            RangedCriticalChance = "Stats/RangedCriticalChance",
            MagicCriticalChance = "Stats/MagicCriticalChance",
            ItemStaminaCostMultiplier = "Stats/ItemStaminaCostMultiplier",
            EquipWeaponActionCooldown = "Stats/EquipWeaponActionCooldown",
            StaminaDepletedTimeMultiplier = "Stats/StaminaDepletedTimeMultiplier",
            SummonsManaDrainMultiplier = "Stats/SummonsManaDrainMultiplier",
            AdditionalScrapChance = "Stats/AdditionalScrapChance",
            PrisonPenaltyMultiplier = "Stats/PrisonPenaltyMultiplier",
            TheftHoldTimeModifier = "Stats/TheftHoldTimeModifier",
            PickpocketHoldTimeModifier = "Stats/PickpocketHoldTimeModifier",
            PickpocketRecoveryChance = "Stats/PickpocketRecoveryChance",
            DualWieldHeavyAttackCostMultiplier = "Stats/DualWieldHeavyAttackCostMultiplier",
            MaxManaReservation = "Stats/MaxManaReservation",
            SummonLimit = "Stats/SummonLimit",
            
            BuffStrength = "Stats/BuffStrength",
            BuffDuration = "Stats/BuffDuration",
            DebuffStrength = "Stats/DebuffStrength",
            DebuffDuration = "Stats/DebuffDuration",
            
            EquipmentLevelBonus = "Stats/EquipmentLevelBonus", 
            ArmorPenaltyMultiplier = "Stats/ArmorPenaltyMultiplier",
            FenceSellBonusMultiplier = "Stats/FenceSellBonusMultiplier",
            CookingLevelBonus = "Stats/CookingLevelBonus",
            AlchemyLevelBonus = "Stats/AlchemyLevelBonus",
            CraftingLevelBonus = "Stats/CraftingLevelBonus",
            UpgradeDiscount = "Stats/UpgradeDiscount", 
            CraftingRequirementModifier = "Stats/CraftingRequirementModifier",
            CraftingSkillBonus = "Stats/CraftingSkillBonus",
            
            // --- Statuses Stats
            BleedBuildup = "Stats/BleedBuildup",
            BleedEffectModifier = "Stats/BleedEffectModifier",
            BurnBuildup = "Stats/BurnBuildup",
            BurnEffectModifier = "Stats/BurnEffectModifier",
            FrenzyBuildup = "Stats/FrenzyBuildup",
            FrenzyEffectModifier = "Stats/FrenzyEffectModifier",
            ConfusionBuildup = "Stats/ConfusionBuildup",
            ConfusionEffectModifier = "Stats/ConfusionEffectModifier",
            CorruptionBuildup = "Stats/CorruptionBuildup",
            CorruptionEffectModifier = "Stats/CorruptionEffectModifier",
            MuteBuildup = "Stats/MuteBuildup",
            MuteEffectModifier = "Stats/MuteEffectModifier",
            PoisonBuildup = "Stats/PoisonBuildup",
            PoisonEffectModifier = "Stats/PoisonEffectModifier",
            SlowBuildup = "Stats/SlowBuildup",
            SlowEffectModifier = "Stats/SlowEffectModifier",
            StunBuildup = "Stats/StunBuildup",
            StunEffectModifier = "Stats/StunEffectModifier",
            WeakBuildup = "Stats/WeakBuildup",
            WeakEffectModifier = "Stats/WeakEffectModifier",

            DrunkBuildup = "Stats/DrunkBuildup",
            DrunkEffectModifier = "Stats/DrunkEffectModifier",
            IntoxicatedBuildup = "Stats/IntoxicatedBuildup",
            IntoxicatedEffectModifier = "Stats/IntoxicatedEffectModifier",
            FullBuildup = "Stats/FullBuildup",
            FullEffectModifier = "Stats/FullEffectModifier",
            
            // --- Stats Summary
            MeleeDamageBonus = "StatsSummary/MeleeDamageBonus",
            RangeDamageBonus = "StatsSummary/RangeDamageBonus",
            MagicDamageBonus = "StatsSummary/MagicDamageBonus",
            ArmorEquipLoad = "StatsSummary/ArmorEquipLoad",
            DamageReductionBonus = "StatsSummary/DamageReductionBonus",
            HealthRegeneration = "StatsSummary/HealthRegeneration",
            MovementSpeed = "StatsSummary/MovementSpeed",

            // - Trade stats
            BuyModifier = "TradeStat/BuyModifier",
            SellModifier = "TradeStat/SellModifier",

            // --- Statuses
            Sin = "Status/Sin",
            Debuff = "Status/Debuff",
            Curse = "Status/Curse",
            Blessing = "Status/Blessing",
            Buff = "Status/Buff",
            TechnicalStatus = "Status/Technical",

            // --- Popups
            PopupPressAnyButton = "Popup/PressAnyButton",
            PopupGameLanguageChangedTitle = "Popup/GameLanguageChangedTitle",
            PopupGameLanguageChanged = "Popup/GameLanguageChanged",
            PopupQuitToTitle = "Popup/QuitGameToTitle",
            PopupQuitToSystem = "Popup/QuitGameToSystem",
            PopupQuitGameTitle = "Popup/QuitGameTitle",
            PopupQuitGame = "Popup/QuitGame",
            PopupLoadGame = "Popup/LoadGame",
            PopupSaveAndQuit = "Popup/SaveAndQuit",
            PopupSavedSlotClear = "Popup/PopupSavedSlotClear",
            PopupSavedSlotOverride = "Popup/PopupSavedSlotOverride",
            PopupNotAppliedSettingsTitle = "Popup/NotAppliedSettingsTitle",
            PopupNotAppliedSettings = "Popup/NotAppliedSettings",
            PopupHeroCreatorClose = "Popup/HeroCreatorClose",
            PopupDefaultSettingsTitle = "Popup/DefaultSettingsTitle",
            PopupDefaultSettings = "Popup/DefaultSettings",
            PopupGraphicsPresetTitle = "Popup/GraphicsPresetTitle",
            PopupGraphicsPresetMessage = "Popup/GraphicsPresetMessage",
            PopupNotSavedWarning = "Popup/NotSavedWarning",
            PopupLastSaveTime = "Popup/LastSaveTime",
            PopupConfirmApplyingChanges = "Popup/ConfirmApplyingChanges",
            PopupOverrideBindingdSettings = "Popup/OverrideBindingSettings",
            PopupOverrideBindingdSettingsTitle = "Popup/OverrideBindingSettingsTitle",
            PopupSelectPreset = "Popup/SelectPreset",
            PopupSelectPresetTitle = "Popup/SelectPresetTitle",
            StartupPopupMessage = "MenuPopup/StartupMessage",
            FastTravelPopupTitle = "Popup/FastTravelTitle",
            FastTravelPopupMessage = "Popup/FastTravelMessage",
            FastTravelOnlyInBonfire = "Popup/FastTravelOnlyInBonfire",
            FastTravelBlockedByCombat = "Popup/FastTravelBlockedByCombat",
            FastTravelBlockedByWater = "Popup/FastTravelBlockedByWater",
            FastTravelBlockedByEncumbrance = "Popup/FastTravelBlockedByEncumbrance",
            FastTravelPossibleButCostsWyrdnightResources = "Popup/FastTravelPossibleButCostsWyrdnightResources",
            FastTravelBlockedByLackOfWyrdnightResources = "Popup/FastTravelBlockedByLackOfWyrdnightResources",
            FailedToEquipItemToLoadout = "Popup/FailedToEquipItemToLoadout",
            LoadoutEquipBlocked = "Popup/LoadoutEquipBlocked",
            PopupDomainErrorTitle = "Popup/DomainError/Title",
            PopupDomainErrorInfo = "Popup/DomainError/Info",
            PopupDomainErrorButton = "Popup/DomainError/Button",
            PopupUnstuckTitle = "Popup/UnstuckTitle",
            PopupUnstuckMessage = "Popup/UnstuckMessage",
            PopupUnstuckFailed = "Popup/UnstuckFailed",
            PopupChangePlantInSlot = "Popup/ChangePlantInSlot",
            PopupChangePlantConfirmResult = "Popup/ChangePlantConfirmResult",
            PopupUnlockHousingRoom = "Popup/UnlockHousingRoom",
            PopupUnlockHousingFurnitureVariant = "Popup/UnlockHousingFurnitureVariant",
            PopupMissingSteamTitle = "Popup/MissingSteamTitle",
            PopupMissingSteamMessage = "Popup/MissingSteamMessage",
            PopupMigrateSavesToSteamTitle = "Popup/MigrateSavesToSteamTitle",
            PopupMigrateSavesToSteamMessage = "Popup/MigrateSavesToSteamMessage",
            
            LevelUp = "Announce/LevelUp",
            NewQuest = "Announce/NewQuest",
            CompletedQuest = "Announce/CompletedQuest",
            FailedQuest = "Announce/FailedQuest",
            QuestUpdate = "Announce/QuestUpdate",
            NewItems = "Announce/NewItems",
            NewJournalEntry = "Announce/NewJournalEntry",
            Good = "Announce/Good",
            Bad = "Announce/Bad",
            FishingFail = "Announce/FishingFail",
            MoreInfoTooltip = "Tooltip/MoreInfoTooltip",
            StolenItem = "Item/StolenItem",
            SketchingFail = "Announce/SketchingFail",
            
            FishingCatch = "Fishing/FishingCatch",
            FishingPull = "Fishing/FishingPull",

            NewLocationDiscovered = "Notification/NewLocationDiscovered",
            QuestNotification = "Notification/QuestNotification",
            QuestNotificationTrack = "Notification/QuestNotificationTrack",
            SkillUpNotification = "Notification/SkillUpNotification",
            FastTravelUnlockedNotification = "Notification/FastTravelUnlockedNotification",
            FastTravelPoint = "Notification/FastTravelPoint",
            LearnedWyrdSkillNotification = "Notification/LearnedWyrdSkillNotification",
            TrespassingEnteredNotification = "Notification/TrespassingEnteredNotification",
            TrespassingTimeToAlert = "Notification/TrespassingTimeToAlert",
            TrespassingAlerted = "Notification/TrespassingAlerted",
            FishTitleNotification = "Notification/FishTitleNotification",
            FishNewTitleNotification = "Notification/FishNewTitleNotification",
            FishItemTitleNotification = "Notification/FishItemTitleNotification",
            FishNewRecordNotification = "Notification/FishNewRecordNotification",
            FishPrevRecordNotification = "Notification/FishPrevRecordNotification",
            NewRecipeUnlocked = "Notification/NewRecipeUnlocked",
            SavingBlocked = "Notification/SavingBlocked",
            SavingBlockedInCombat = "Notification/SavingBlockedInCombat",
            SavingBlockedOther = "Notification/SavingBlockedOther",
            LoadingBlocked = "Notification/LoadingBlocked",
            LoadingBlockedWhileSaving = "Notification/LoadingBlockedWhileSaving",
            LoadingBlockedOther = "Notification/LoadingBlockedOther",
            WyrdNightSurprisedYou = "Notification/WyrdNightSurprisedYou",
            WyrdNightSomethingInterruptedYourSleep = "Notification/WyrdNightSomethingInterruptedYourSleep",
            GoToBonfire = "Notification/GoToBonfire",
            ArthurMemories = "Notification/ArthurMemories",

            // --- Story
            StoryGiveItem = "Story/GiveItem",
            StoryGetItem = "Story/GetItem",
            StoryCurrentlyEquipped = "Story/CurrentlyEquipped",
            StoryPickItem = "Story/PickItem",
            StoryRisingCost = "Story/RisingCost",
            StoryInInventory = "Story/InInventory",
            StoryQuestAdded = "Story/QuestAdded",
            StoryQuestCompleted = "Story/QuestCompleted",
            StoryObjectiveAdded = "Story/ObjectiveAdded",
            StoryObjectiveUpdated = "Story/ObjectiveUpdated",
            StoryObjectiveFailed = "Story/ObjectiveFailed",

            // --- Settings
            AdditionalSettings = "Settings/AdditionalSettings",
            SettingsApply = "Settings/Apply",
            SettingsRestoreDefaults = "Settings/RestoreDefaults",
            SettingsRestartRequired = "Settings/RestartRequired",
            SettingsRestartRequiredDesc = "Settings/RestartRequiredDesc",
            SettingsPreviousOption = "Settings/PreviousOption",
            SettingsNextOption = "Settings/NextOption",
            SettingsToggle = "Settings/Toggle",
            SettingsSliderPlus = "Settings/SliderPlus",
            SettingsSliderMinus = "Settings/SliderMinus",
            SettingsButtonAction = "Settings/ButtonAction",

            SettingsGeneralTab = "Settings/GeneralTab",
            SettingsGameplayTab = "Settings/GameplayTab",
            SettingsAudioTab = "Settings/AudioTab",
            SettingsDisplayTab = "Settings/DisplayTab",
            SettingsGraphicTab = "Settings/GraphicTab",
            SettingsControlsTab = "Settings/ControlsTab",
            SettingsAccessibilityTab = "Settings/AccessibilityTab",

            SettingsGraphicPreset = "Settings/GraphicsPreset",
            SettingsGeneral = "Settings/General",
            SettingsTooltipGeneral = "Settings/Tooltip/General",
            SettingsNone = "Settings/None",
            SettingsPresetPerformance = "Settings/Performance",
            SettingsPresetQuality = "Settings/Quality",
            SettingsPresetLow = "Settings/Low",
            SettingsPresetMedium = "Settings/Medium",
            SettingsPresetHigh = "Settings/High",
            SettingsPresetUltra = "Settings/Ultra",
            SettingsPresetCustom = "Settings/Custom",
            SettingsSSAO = "Settings/SSAO",
            SettingsFog = "Settings/Fog",
            SettingsAntiAliasing = "Settings/AntiAliasing",
            SettingsUpScaling = "Settings/UpScaling",
            SettingsFXAA = "Settings/FXAA",
            SettingsSMAA = "Settings/SMAA",
            SettingsTAA = "Settings/TAA",
            SettingsFSR = "Settings/FSR",
            SettingsSTP = "Settings/STP",
            SettingsDLSS = "Settings/DLSS",
            SettingsUpScalingQuality = "Settings/UpScalingQuality",
            SettingsQuality = "Settings/Quality",
            SettingsMotionBlur = "Settings/MotionBlur",
            SettingsMotionBlurIntensity = "Settings/MotionBlurIntensity",
            SettingsChromaticAberration = "Settings/ChromaticAberration",
            SettingsDOF = "Settings/DOF",
            SettingsTextureQuality = "Settings/TextureQuality",
            SettingsVSync = "Settings/VSync",
            SettingsGamma = "Settings/Gamma",
            SettingsContrast = "Settings/Contrast",
            SettingsGammaMessage = "Settings/GammaMessage",
            SettingsVegetation = "Settings/Vegetation",
            SettingsDistanceCulling = "Settings/DistanceCulling",
            SettingsMipmapsBias = "Settings/MipmapsBias",
            SettingsResolution = "Settings/Resolution",
            SettingsDisplayNumber = "Settings/DisplayNumber",
            SettingsFullscreen = "Settings/Fullscreen",
            SettingsShowIntroVideos = "Settings/ShowIntroVideos",
            SettingsAimAssist = "Settings/AimAssist",
            SettingsAimAssistMicrosoft = "XboxSettings/AimAssist",
            SettingsTutorials = "Settings/Tutorials",
            SettingsDialogueAutoAdvance = "Settings/DialogueAutoAdvance",
            SettingsTooltipDialogueAutoAdvance = "Settings/Tooltip/DialogueAutoAdvance",
            SettingReverseHands = "Settings/ReverseHands",
            SettingCameraKillEffect = "Settings/SettingCameraKillEffect",
            SettingStealthKillCamera = "Settings/StealthKillCamera",
            SettingCriticalKillCamera = "Settings/CriticalKillCamera",
            SettingWeakspotKillCamera = "Settings/WeakspotKillCamera",
            SettingsShowNewThings = "Settings/ShowNewThings",
            SettingsCollectData = "Settings/CollectData",
            SettingsPrivacyPolicy = "Settings/PrivacyPolicy",
            SettingsCredits = "Settings/Credits",
            SettingsBugReporting = "Settings/BugReporting",
            SettingsTargetFps = "Settings/TargetFps",
            SettingsUnlimitedFps = "Settings/UnlimitedFps",
            SettingsBorderless = "Settings/Borderless",
            SettingsWindowed = "Settings/Windowed",
            SettingsPressNewKey = "Settings/PressNewKey",
            SettingsKeyAlreadySet = "Settings/KeyAlreadySet",
            SettingsLanguageSet = "Settings/LanguageSet",
            SettingsDisableAudioInBackground = "Settings/DisableAudioInBackground",
            SettingsInfluencerMode = "Settings/InfluencerMode",
            SettingsCameraSensitivity = "Settings/CameraSensitivity",
            GamepadDeadZone = "Settings/GamepadDeadZone",
            GamepadDeadZoneMicrosoft = "XboxSettings/GamepadDeadZone",
            SettingsPadVibrations = "Settings/PadVibrations",
            SettingsPadVibrationsMicrosoft = "XboxSettings/PadVibrations",
            SettingsAdaptiveTriggers = "Settings/SettingsAdaptiveTriggers",
            SettingsAdaptiveTriggersMicrosoft = "XboxSettings/SettingsAdaptiveTriggers",
            SettingsConsoleUI = "Settings/SettingsConsoleUI",
            SettingsFOV = "Settings/FOV",
            SettingsEnableFOVChanges = "Settings/EnableFOVChanges",
            SettingsShowNames = "Settings/ShowNames",
            SettingsFOVMultiplier = "Settings/FOVMultiplier",
            SettingsFOVTooltip = "Settings/FOVTooltip",
            SettingsCameraInvert = "Settings/CameraInvert",
            SettingsGliderPitchInvert = "Settings/GliderPitchInvert",
            SettingsDifficulty = "Settings/Difficulty",
            SettingsVfxQuality = "Settings/VfxQuality",
            SettingsShadows = "Settings/Shadows",
            SettingsShadowsDistance = "Settings/ShadowsDistance",
            SettingsContactShadows = "Settings/ContactShadows",
            SettingsTooltipContactShadows = "Settings/Tooltip/ContactShadows",
            SettingsContactShadowsDistance = "Settings/ContactShadowsDistance",
            SettingsReflections = "Settings/Reflections",
            SettingsSSS = "Settings/SSS",
            SettingsSSSQuality = "Settings/SSSQuality",
            SettingsTooltipSSS = "Settings/Tooltip/SSS",
            SettingsBindingHold = "Settings/Binding/Hold",
            SettingsBindingToggle = "Settings/Binding/Toggle",
            SettingsCPUAffinity = "Settings/CPUAffinity",
            SettingsCPUAffinityTooltip = "Settings/CPUAffinityTooltip",
            SettingReverseHandsTooltip = "Settings/Tooltip/ReverseHands",
            CollectDataSettingTooltip = "Settings/Tooltip/CollectData",
            DifficultySettingTooltip = "Settings/Tooltip/Difficulty",
            InverseHandsSettingTooltip = "Settings/Tooltip/InverseHands", 
            CameraKillEffectSettingTooltip = "Settings/Tooltip/CameraKillEffect",
            HudScaleSettingTooltip = "Settings/Tooltip/HudScale",
            HeroBarsScaleSettingTooltip = "Settings/Tooltip/HeroBarsScaleSettingTooltip",
            CompassScaleSettingTooltip = "Settings/Tooltip/CompassScaleSettingTooltip",
            MenuUIScaleSettingTooltip = "Settings/Tooltip/MenuUIScale",
            ShowCompassSettingTooltip = "Settings/Tooltip/ShowCompass",
            ShowUIHUDSettingTooltip = "Settings/Tooltip/ShowUIHUD",
            ShowUIQuestsSettingTooltip = "Settings/Tooltip/ShowUIQuests",
            SettingsScreenShake = "Settings/ScreenShake",
            ScreenShakeProactiveSettingTooltip = "Settings/Tooltip/ScreenShakeProactive",
            ScreenShakeReactiveSettingTooltip = "Settings/Tooltip/ScreenShakeReactive",
            HeadBobbingSettingTooltip = "Settings/Tooltip/HeadBobbingSetting",
            EnviroSubtitlesSettingTooltip = "Settings/Tooltip/EnviroSubtitles",
            ShowNamesSettingTooltip = "Settings/Tooltip/ShowNames",
            BackgroundAudioSettingTooltip = "Settings/Tooltip/BackgroundAudio",
            FovChangesSettingTooltip = "Settings/Tooltip/FovChanges",
            InvertedGlidingPitchSettingTooltip = "Settings/Tooltip/InvertedGlidingPitch",
            PerspectiveSettingTooltip = "Settings/Tooltip/Perspective",

            SettingsUseToolsWithoutPrompt = "Settings/UseToolsWithoutPrompt",
            SettingsUseToolsWithoutPromptMining = "Settings/UseToolsWithoutPrompt/Mining",
            SettingsUseToolsWithoutPromptDigging = "Settings/UseToolsWithoutPrompt/Digging",
            SettingsUseToolsWithoutPromptLumbering = "Settings/UseToolsWithoutPrompt/Lumbering",
            SettingsUseToolsWithoutPromptFishing = "Settings/UseToolsWithoutPrompt/Fishing",
            
            SettingsDisableHeroHelmet = "Settings/DisableHeroHelmet",

            // --- Audio Settings
            SettingsMasterVolume = "Settings/MASTERVolume",
            SettingsMusicVolume = "Settings/MUSICVolume",
            SettingsSFXVolume = "Settings/SFXVolume",
            SettingsUIVolume = "Settings/UIVolume",
            SettingsVoiceVolume = "Settings/VOICEVolume",
            SettingsVideoVolume = "Settings/VIDEOVolume",
            Never = "Settings/Never",
            OnlyOutsideOfDialogues = "Settings/OnlyOutsideOfDialogues",
            Always = "Settings/Always",
            DialogueWithActorName = "Settings/DialogueWithActorName",
            UnknownActor = "Settings/UnknownActor",
            
            // --- AutoSave
            SettingsAutoSave = "Settings/AutoSave",
            SettingsQuickUseWheel = "Settings/QuickUseWheel",
            SettingsAutoSaveFrequency = "Settings/AutoSaveFrequency",
            OneMinute = "Settings/OneMinute",
            ThreeMinutes = "Settings/ThreeMinutes",
            FiveMinutes = "Settings/FiveMinutes",
            TenMinutes = "Settings/TenMinutes",
            // --- UI Settings
            SettingsUICompass = "Settings/UICompass",
            SettingsShowUIHUD = "Settings/ShowUIHUD",
            SettingsShowUIQuests = "Settings/ShowUIQuests",
            // --- Accessibility Settings
            SettingsFontSize = "Settings/FontSize",
            SettingsHUDScale = "Settings/HUDScale",
            SettingsHUDHeroBarsScale = "Settings/HUDHeroBarsScale",
            SettingsHUDCompassScale = "Settings/HUDCompassScale",
            SettingsMenuUIScale = "Settings/MenuUIScale",
            SettingsSimpleFont = "Settings/SimpleFont",
            SettingsFullCaptions = "Settings/FullCaptions",
            SettingsScreenShakeProactive = "Settings/ScreenShakeProactive",
            SettingsScreenShakeReactive = "Settings/ScreenShakeReactive",
            HeadBobbingSetting = "Settings/HeadBobbingSetting",
            SettingsSubtitles = "Settings/Subtitles",
            SettingsEnviroSubtitles = "Settings/EnviroSubtitles",
            FontSizeVerySmall = "Settings/FontVerySmall",
            FontSizeSmall = "Settings/FontSmall",
            FontSizeMedium = "Settings/FontMedium",
            FontSizeBig = "Settings/FontBig",
            FontSizeHuge = "Settings/FontHuge",
            DialogueSubtitlesColor = "Settings/DialogueSubtitlesColor",
            SubtitlesBackgroundOpacity = "Settings/SubtitlesBackgroundOpacity",
            HudBackground = "Settings/HudBackground",
            HudBackgroundOpacity = "Settings/HudBackgroundOpacity",
            SettingsPerspective = "Settings/Perspective",
            SettingsThirdPersonPopupTitle = "Settings/SettingsThirdPersonPopupTitle",
            SettingsThirdPersonPopupMessage = "Settings/SettingsThirdPersonPopupMessage",
            SettingsPerspectiveTPP = "Settings/PerspectiveTPP",
            SettingsPerspectiveFPP = "Settings/PerspectiveFPP",
            SettingsTppPerspectiveCameraDistance = "Settings/TppPerspectiveCameraDistance",
            SettingsScreenShakeAll = "Settings/SettingsScreenShakeAll",
            SettingsScreenShakeAllProactive = "Settings/ScreenShakeAll/Proactive",
            SettingsScreenShakeAllProactiveAndReactive = "Settings/ScreenShakeAll/ProactiveReactive",
            SettingsDialogueSubtitlesOption = "Settings/DialogueSubtitlesOption",
            SettingsDialogueSubtitles = "Settings/DialogueSubtitles",
            SettingsDialogueEnvironmentSubtitles = "Settings/DialogueEnvironmentSubtitles",
            SettingsDialogueSubtitlesDescription = "Settings/Description/DialogueSubtitles",
            SettingsFontSizeDescription = "Settings/Description/FontSize",
            SettingsConsoleUIDescription = "Settings/Description/ConsoleUI",
            SettingsDialogueAutoAdvanceDescription = "Settings/Description/DialogueAutoAdvance",
            SettingsScreenShakeAllDescription = "Settings/Description/ScreenShakeAll",
            SettingsAimAssistDescription = "Settings/Description/AimAssist",
            SettingsAimAssistMicrosoftDescription = "Settings/Description/AimAssistMicrosoft",
            SettingsPerspectiveDescription = "Settings/Description/Perspective",
            GeneralGameSettingsTitle = "Settings/GeneralGameSettingsTitle",
            
            // --- Keywords
            ManaShield = "Keyword/ManaShield",
            ManaShieldRetaliation = "Keyword/ManaShieldRetaliation",
            MeleeRetaliation = "Keyword/MeleeRetaliation",
            ManaShieldDesc = "Keyword/ManaShieldDesc",
            Lifesteal = "Keyword/Lifesteal",
            LifestealDesc = "Keyword/LifestealDesc",
            Buildup = "Keyword/Buildup",
            BuildupDesc = "Keyword/BuildupDesc",
            StatusBleed = "Keyword/StatusBleed",
            StatusBleedDesc = "Keyword/StatusBleedDesc",
            StatusBurn = "Keyword/StatusBurn",
            StatusBurnDesc = "Keyword/StatusBurnDesc",
            StatusInferno = "Keyword/StatusInferno",
            StatusInfernoDesc = "Keyword/StatusInfernoDesc",
            StatusChilled = "Keyword/StatusChilled",
            StatusChilledDesc = "Keyword/StatusChilledDesc",
            StatusFrozen = "Keyword/StatusFrozen",
            StatusFrozenDesc = "Keyword/StatusFrozenDesc",
            StatusConfusion = "Keyword/StatusConfusion",
            StatusConfusionDesc = "Keyword/StatusConfusionDesc",
            StatusCorruption = "Keyword/StatusCorruption",
            StatusCorruptionDesc = "Keyword/StatusCorruptionDesc",
            StatusMute = "Keyword/StatusMute",
            StatusMuteDesc = "Keyword/StatusMuteDesc",
            StatusBlind = "Keyword/StatusBlind",
            StatusBlindDesc = "Keyword/StatusBlindDesc",
            StatusPoison = "Keyword/StatusPoison",
            StatusPoisonDesc = "Keyword/StatusPoisonDesc",
            StatusSlow = "Keyword/StatusSlow",
            StatusSlowDesc = "Keyword/StatusSlowDesc",
            StatusStun = "Keyword/StatusStun",
            StatusStunDesc = "Keyword/StatusStunDesc",
            StatusWeak = "Keyword/StatusWeak",
            StatusWeakDesc = "Keyword/StatusWeakDesc",
            StatusDrunk = "Keyword/StatusDrunk",
            StatusDrunkDesc = "Keyword/StatusDrunkDesc",
            StatusIntoxicated = "Keyword/StatusIntoxicated",
            StatusIntoxicatedDesc = "Keyword/StatusIntoxicatedDesc",
            StatusFull = "Keyword/StatusFull",
            StatusFullDesc = "Keyword/StatusFullDesc",
            StatusBerserk = "Keyword/StatusBerserk",
            StatusBerserkDesc = "Keyword/StatusBerserkDesc",
            StatusHaste = "Keyword/StatusHaste",
            StatusHasteDesc = "Keyword/StatusHasteDesc",
            StatusRage = "Keyword/StatusRage",
            StatusRageDesc = "Keyword/StatusRageDesc",
            StatusRejuvenated = "Keyword/StatusRejuvenated",
            StatusRejuvenatedDesc = "Keyword/StatusRejuvenatedDesc",
            StatusOverexerted = "Keyword/StatusOverexerted",
            StatusOverexertedDesc = "Keyword/StatusOverexertedDesc",
            StatusUntouchable = "Keyword/StatusUntouchable",
            StatusUntouchableDesc = "Keyword/StatusUntouchableDesc",
            StatusWellRested = "Keyword/StatusWellRested",
            StatusWellRestedDesc = "Keyword/StatusWellRestedDesc",
            StatusResilienceRush = "Keyword/StatusResilienceRush",
            StatusResilienceRushDesc = "Keyword/StatusResilienceRushDesc",
            StatusFrenzy = "Keyword/StatusFrenzy",
            StatusFrenzyDesc = "Keyword/StatusFrenzyDesc",
            
            WeakSpot = "Keyword/WeakSpot",
            WeakSpotDesc = "Keyword/WeakSpotDesc",
            CriticalHit = "Keyword/CriticalHit",
            CriticalHitDesc = "Keyword/CriticalHitDesc",
            SneakDamage = "Keyword/SneakDamage",
            SneakDamageDesc = "Keyword/SneakDamageDesc",
            Staggered = "Keyword/Staggered",
            StaggeredDesc = "Keyword/StaggeredDesc",
            ConsecutiveHit = "Keyword/ConsecutiveHit",
            ConsecutiveHitDesc = "Keyword/ConsecutiveHitDesc",

            ToolMining = "Keyword/ToolMining",
            ToolMiningDesc = "Keyword/ToolMiningDesc",
            ToolDigging = "Keyword/ToolDigging",
            ToolDiggingDesc = "Keyword/ToolDiggingDesc",
            ToolFishing = "Keyword/ToolFishing",
            ToolFishingDesc = "Keyword/ToolFishingDesc",
            ToolSketching = "Keyword/ToolSketching",
            ToolSketchingDesc = "Keyword/ToolSketchingDesc",
            ToolSpyglassing = "Keyword/ToolSpyglassing",
            ToolSpyglassingDesc = "Keyword/ToolSpyglassingDesc",
            ToolGliding = "Keyword/ToolGliding",
            ToolGlidingDesc = "Keyword/ToolGlidingDesc",
            ToolLumbering = "Keyword/ToolLumbering",
            ToolLumberingDesc = "Keyword/ToolLumberingDesc",

            // --- Difficulties
            DifficultyStory = "Difficulty/Story",
            DifficultyEasy = "Difficulty/Easy",
            DifficultyNormal = "Difficulty/Normal",
            DifficultyHard = "Difficulty/Hard",
            DifficultySurvival = "Difficulty/Survival",
            DifficultyHardcore = "Difficulty/Hardcore",
            DifficultyStoryDesc = "DifficultyDesc/Story",
            DifficultyEasyDesc = "DifficultyDesc/Easy",
            DifficultyNormalDesc = "DifficultyDesc/Normal",
            DifficultyHardDesc = "DifficultyDesc/Hard",
            DifficultySurvivalDesc = "DifficultyDesc/Survival",
            DifficultyHardcoreDesc = "DifficultyDesc/Hardcore",
            
            // --- Inventory Types
            Consumable = "InventoryType/Consumable",
            Crafting = "InventoryType/Crafting",
            AudioLogs = "InventoryType/AudioLogs",
            QuestItems = "InventoryType/QuestItems",
            CombatItems = "InventoryType/CombatItems",
            WeaponItems = "InventoryType/WeaponItems",
            ArmorItems = "InventoryType/ArmorItems",
            OtherItems = "InventoryType/OtherItems",
            Lockpick = "Inventory/Item/Lockpick",
            Key = "Inventory/Item/Key",

            // --- Character Tabs
            CharacterTabCharacter = "CharacterTab/Character",
            CharacterTabOverview = "CharacterTab/Overview",
            CharacterTabReputation = "CharacterTab/Reputation",
            CharacterTabInventory = "CharacterTab/Inventory",
            CharacterTabEquipment = "CharacterTab/Equipment",
            CharacterTabBag = "CharacterTab/Bag",
            CharacterTabMap = "CharacterTab/Map",
            CharacterTabQuests = "CharacterTab/Quests",
            CharacterTabJournal = "CharacterTab/Journal",
            CharacterTabTalents = "CharacterTab/Talents",
            CharacterStatsSummary = "CharacterTab/StatsSummary",
            CharacterTabWyrdArthur = "CharacterTab/WyrdArthur",
            CharacterTabWyrdArthurSouls = "CharacterTab/WyrdArthurSouls",

            // --- Items Tabs
            ItemsTabAll = "ItemsTab/All",
            ItemsTabRecent = "ItemsTab/Recent",

            ItemsTabOneHanded = "ItemsTab/OneHanded",
            ItemsTabTwoHanded = "ItemsTab/TwoHanded",
            ItemsTabMagic = "ItemsTab/Magic",
            ItemsTabRanged = "ItemsTab/Ranged",
            ItemsTabArrows = "ItemsTab/Arrows",
            ItemsTabShields = "ItemsTab/Shields",

            ItemsTabCrafting = "ItemsTab/Crafting",
            ItemsTabConsumable = "ItemTab/Consumable",
            ItemsTabReadable = "ItemTab/Readable",
            ItemsTabQuestItems = "ItemTab/QuestItems",
            ItemsTabOther = "ItemsTab/Other",

            ItemsTabWeapons = "ItemsTab/Weapons",
            ItemsTabArmor = "ItemsTab/Armor",
            ItemsTabGear = "ItemsTab/Gear",
            ItemsTabGems = "ItemsTab/Gems",
            ItemsTabJewelry = "ItemsTab/Jewelry",
            ItemsTabRecipes = "ItemsTab/Recipes",
            ItemsTabComponent = "ItemsTab/Component",
            ItemsTabKeys = "ItemsTab/Keys",

            // --- Crafting Tabs
            ExperimentalCookingTab = "CraftingTab/ExperimentalCooking",
            RecipeCookingTab = "CraftingTab/RecipeCooking",
            ExperimentalAlchemyTab = "CraftingTab/ExperimentalAlchemy",
            RecipeAlchemyTab = "CraftingTab/RecipeAlchemy",
            RecipeHandcraftingTab = "CraftingTab/RecipeHandcrafting",
            
            ExperimentalCookingTabDescription = "CraftingTab/ExperimentalCookingDescription",
            RecipeCookingTabDescription = "CraftingTab/RecipeCookingDescription",
            ExperimentalAlchemyTabDescription = "CraftingTab/ExperimentalAlchemyDescription",
            RecipeAlchemyTabDescription = "CraftingTab/RecipeAlchemyDescription",
            RecipeHandcraftingTabDescription = "CraftingTab/RecipeHandcraftingDescription",
            
            // --- Shop Tabs
            ShopTabBuyDescription = "ShopTab/BuyDescription",
            ShopTabSellDescription = "ShopTab/SellDescription",
            ShopTabBuybackDescription = "ShopTab/BuybackDescription",

            //Crafting
            CraftingAdjustIngredientsInfo = "Crafting/AdjustIngredientsInfo",
            CraftingOutcome = "Crafting/Outcome",
            CraftingRecipeLearned = "Crafting/RecipeLearned",
            CraftingPromptHoldToCraft = "Crafting/PromptHoldToCraft",
            CraftingPromptCannotCraft = "Crafting/PromptCannotCraft",
            CraftingPromptCraft = "Crafting/PromptCraft",
            CraftingPromptCraftOne = "Crafting/PromptCraftOne",
            CraftingPromptCraftMany = "Crafting/PromptCraftMany",
            AlchemyZeroHint = "Crafting/AlchemyZeroHint",
            AlchemyFirstHint = "Crafting/AlchemyFirstHint",
            AlchemySecondHint = "Crafting/AlchemySecondHint",
            AlchemyThirdHint = "Crafting/AlchemyThirdHint",
            AlchemyFourthHint = "Crafting/AlchemyFourthHint",
            SharpeningRequiredIngredients = "Crafting/SharpeningRequiredIngredients",
            ItemCrafted = "Crafting/ItemCrafted",
            NewRecipeDiscovered = "Crafting/NewRecipeDiscovered",
            PutRandomIngredientsIntoThePot = "Crafting/PutRandomIngredientsIntoThePot",
            RandomIngredientsDescription= "Crafting/RandomIngredientsDescription",
            Ingredients = "Crafting/Ingredients",
            AvailableIngredients = "Crafting/AvailableIngredients",
            AvailableRecipes = "Crafting/AvailableRecipes",
            IngredientsUnavailable = "Crafting/IngredientsUnavailable",
            IdentifyTab = "Crafting/Identify",
            IdentifyTabDescription = "Crafting/IdentifyTabDescription",
            IdentifyRequired = "Crafting/IdentifyRequired",
            ArmorWeightReductionTab = "Crafting/ArmorWeightReduction",
            ExceptedCraftingOutcome = "Crafting/ExceptedCraftingOutcome",
            ExceptedCraftingChanceForWorse = "Crafting/ExceptedCraftingChanceForWorse",
            ExceptedCraftingChanceForBetter = "Crafting/ExceptedCraftingChanceForBetter",

            // --- Relics Tabs
            RelicsPromptAddSlot = "Relics/RelicsPromptAddSlot",
            RelicsPromptAttach = "Relics/GemsPromptAttach",
            RelicsPromptRetrieve = "Relics/RelicsPromptRetrieve",
            RelicsPromptSharpen = "Relics/RelicsPromptSharpen",
            RelicsPromptIdentify = "Relics/RelicsPromptIdentify",
            RelicsPromptReduceWeight = "Relics/RelicsPromptReduceWeight",
            UpgradeChance = "Relics/UpgradeChance",
            UpgradeSuccessful = "Relics/UpgradeSuccessful",
            UpgradeFailed = "Relics/UpgradeFailed",
            PickAnItem = "Relics/PickAnItem",
            PickAGem = "Relics/PickAGem",
            NoItemsAvailable = "Relics/NoItemsAvailable",
            NoGemsAvailable = "Relics/NoGemsAvailable",
            
            ManageRelicsTab = "Relics/Manage",
            AddRelicTab = "Relics/Add",
            RetrieveTab = "Relics/Retrieve",
            GemAttachingTab = "Relics/GemAttaching",
            SharpenTab = "Relics/Sharpen",
            RelicSlot = "Relics/RelicSlot",
            GearSlot = "Relics/GearSlot",

            // --- Items Comparer
            ItemsComparerByLevelAscending = "ItemsComparer/ByLevelAscending",
            ItemsComparerByLevelDescending = "ItemsComparer/ByLevelDescending",
            ItemsComparerByQualityAscending = "ItemsComparer/ByQualityAscending",
            ItemsComparerByQualityDescending = "ItemsComparer/ByQualityDescending",
            ItemsComparerByQuantityAscending = "ItemsComparer/ByQuantityAscending",
            ItemsComparerByQuantityDescending = "ItemsComparer/ByQuantityDescending",
            ItemsComparerByPriceAscending = "ItemsComparer/ByPriceAscending",
            ItemsComparerByPriceDescending = "ItemsComparer/ByPriceDescending",
            ItemsComparerByWeightAscending = "ItemsComparer/ByWeightAscending",
            ItemsComparerByWeightDescending = "ItemsComparer/ByWeightDescending",
            ItemsComparerByDamageDescending = "ItemsComparer/ByDamageDescending",
            ItemsComparerByArmorDescending = "ItemsComparer/ByArmorDescending",
            ItemsComparerByNewestAscending = "ItemsComparer/ByNewestAscending",
            ItemsComparerByNewestDescending = "ItemsComparer/ByNewestDescending",
            ItemsComparerByBlockDescending = "ItemsComparer/ByBlockDescending",

            // --- Recipe Tabs
            Recipes = "RecipeTabs/Recipes",

            // --- Recipe Comparer
            RecipeComparerByIngredientCountAscending = "RecipeComparer/ByIngredientCountAscending",
            RecipeComparerByIngredientCountDescending = "RecipeComparer/ByIngredientCountDescending",
            RecipeComparerAlphabeticallyAscending = "RecipeComparer/AlphabeticallyAscending",
            RecipeComparerAlphabeticallyDescending = "RecipeComparer/AlphabeticallyDescending",
            RecipeComparerTierAscending = "RecipeComparer/TierAscending",
            RecipeComparerTierDescending = "RecipeComparer/TierDescending",
            RecipeComparerByPriceAscending = "RecipeComparer/ByPriceAscending",
            RecipeComparerByPriceDescending = "RecipeComparer/ByPriceDescending",
            RecipeComparerByWeightAscending = "RecipeComparer/ByWeightAscending",
            RecipeComparerByWeightDescending = "RecipeComparer/ByWeightDescending",
            
            // --- Journal
            JournalTabBestiary = "JournalTab/Bestiary",
            JournalTabTutorials = "JournalTab/Tutorials",
            JournalTabCharacters = "JournalTab/Characters",
            JournalTabLore = "JournalTab/Lore",
            JournalNoEntries = "Journal/NoEntries",
            JournalEntries = "Journal/Entries",
            FishCurrentRecordJournal = "Journal/FishCurrentRecord",
            
            // --- Item Types
            ItemTypeOneHanded = "ItemType/OneHanded",
            ItemTypeTwoHanded = "ItemType/TwoHanded",
            ItemTypeMagic = "ItemType/Magic",
            ItemTypeShield = "ItemType/Shield",
            ItemTypeRod = "ItemType/Rod",
            ItemTypeBow = "ItemType/Bow",
            ItemTypeArrow = "ItemType/Arrow",
            ItemTypeThrowable = "ItemType/Throwable",
            ItemTypeArmorGem = "ItemType/ArmorGem",
            ItemTypeWeaponGem = "ItemType/WeaponGem",
            
            ItemTypeCuirass = "ItemType/Cuirass",
            ItemTypeHelmet = "ItemType/Helmet",
            ItemTypeGauntlets = "ItemType/Gauntlets",
            ItemTypeGreaves = "ItemType/Greaves",
            ItemTypeBoots = "ItemType/Boots",
            ItemTypeBack = "ItemType/Back",
            
            ItemTypeRing = "ItemType/Ring",
            ItemTypeAmulet = "ItemType/Amulet",

            ItemTypeBuffApplier = "ItemType/BuffApplier",
            ItemTypeConsumable = "ItemType/Consumable",
            ItemTypeCraftingReagent = "ItemType/CraftingReagent",

            ItemTypeDish = "ItemType/Dish",
            ItemTypePotion = "ItemType/Potion",

            ItemTypeRecipe = "ItemType/Recipe",

            ItemTypeReadable = "ItemType/Readable",

            ItemTypeTool = "ItemType/Tool",
            ItemTypeKey = "ItemType/Key",

            ItemTypeOther = "ItemType/Other",
            ItemTypeGarbage = "ItemType/Garbage",
            ItemTypeQuest = "ItemType/Quest",
            
            ItemTypeHorseArmor = "ItemType/HorseArmor",

            // --- Magic cast
            MagicLightCast = "Magic/LightCast",
            MagicHeavyCast = "Magic/HeavyCast",
            
            // --- Magic types
            MagicTypeAoE = "MagicType/AoE",
            MagicTypeBuff = "MagicType/Buff",
            MagicTypeProjectile = "MagicType/Projectile",
            MagicTypeSummon = "MagicType/Summon",
            MagicTypeTrap = "MagicType/Trap",
            MagicTypeRay = "MagicType/Ray",
            MagicTypeChanneled = "MagicType/Channeled",

            // --- Units
            UnitDamage = "Unit/Damage",
            UnitDamagePerSecond = "Unit/DamagePerSecond",
            UnitArmor = "Unit/Armor",
            UnitBlock = "Unit/Block",

            // --- UI
            UIGenericBack = "UI/Generic/Back",
            UIGenericToggle = "UI/Generic/Toggle",
            UIGenericToggleUI = "UI/Generic/ToggleUI",
            UIGenericToggleCamera = "UI/Generic/ToggleCamera",
            UIGenericUse = "UI/Generic/Use",
            UIGenericUnsavedChangesPopup = "UI/Generic/UnsavedChanges",
            UIGenericConfirmChangesPopup = "UI/Generic/Confirm",

            UIGenericOn = "UI/Generic/On",
            UIGenericOff = "UI/Generic/Off",
            UIGenericApply = "UI/Generic/Apply",
            UIGenericMarkAllAsSeen = "UI/Generic/MarkAllAsSeen",
            UIGenericReadMore = "UI/Generic/ReadMore",
            
            UIItemsChangeSorting = "UI/Items/ChangeSorting",
            UIItemsChangeFilter = "UI/Items/ChangeFilter",
            UIItemsSelect = "UI/Items/Select",
            UIItemsEquip = "UI/Items/Equip",
            UIItemsUnequip = "UI/Items/Unequip",
            UIItemsDropItem = "UI/Items/DropItem",
            UIItemsUse = "UI/Items/Use",
            UIItemsEat = "UI/Items/Eat",
            UIItemsRead = "UI/Items/Read",
            UIItemsEmptyGemSlot = "UI/Items/EmptyGemSlot",
            
            EqNoArmorAndJewelery = "UI/Items/NoArmorAndJewelery",
            EqNoWeapon = "UI/Items/NoWeapon",
            EqNoFoodAndPotion = "UI/Items/NoFoodAndPotion",

            UILoadout = "UI/Loadouts/Loadout",
            UILoadoutSelected = "UI/Loadouts/Selected",
            UILoadoutAccessories = "UI/Loadouts/Accessories",
            UILoadoutRightHand = "UI/Loadouts/RightHand",
            UILoadoutLeftHand = "UI/Loadouts/LeftHand",

            UILoadoutArmorWeight = "UI/Loadouts/ArmorWeight",
            UILoadoutArmorTitle = "UI/Loadouts/Armor",
            UILoadoutArmorDescription = "UI/Loadouts/ArmorDescription",
            UILoadoutQuickSlotsTitle = "UI/Loadouts/QuickSlots",
            UILoadoutQuickSlotsDescription = "UI/Loadouts/QuickSlotsDescription",
            UILoadoutWeaponTitle = "UI/Loadouts/WeaponTitle",
            UILoadoutWeaponDescription = "UI/Loadouts/WeaponDescription",
            UILoadoutAutoFillSlotsTitle = "UI/Loadouts/AutoFillSlotsTitle",
            UILoadoutAutoFillSlotsDescription = "UI/Loadouts/AutoFillSlotsDescription",
            
            UIIncrease = "UI/Generic/Increase",
            UIDecrease = "UI/Generic/Decrease",
            
            UITalentsNextLevel = "UI/Talents/NextLevel",
            UITalentsAcquire = "UI/Talents/Acquire",
            UITalentsReset = "UI/Talents/Reset",
            UITalentFireplaceRequired = "UI/Talents/FireplaceRequired",
            UITalentTreeLevel = "UI/Talents/TreeLevel",
            UITalentTreeRequireTreeLevel = "UI/Talents/RequireTreeLevel",

            UIMapPlaceCustomMarker = "UI/Map/PlaceCustomMap",
            UIMapRemoveCustomMarker = "UI/Map/RemoveCustomMap",
            UIMapMove = "UI/Map/Move",
            UIMapZoom = "UI/Map/Zoom",

            UIShopCantAfford = "UI/Shop/CantAfford",
            
            UIStoragePut = "UI/Storage/Put",
            UIStorageTake = "UI/Storage/Take",
            
            UIItemsBag = "UI/Items/Bag",
            UIItemsShop = "UI/Items/Shop",
            
            UIFileIntegrityProgress = "UI/FileIntegrity/Progress",
            UIFileIntegrityFailedTitle = "UI/FileIntegrity/FailedTitle",
            UIFileIntegrityFailedMessageSteam = "UI/FileIntegrity/FailedMessage/Steam",
            UIFileIntegrityFailedMessageGog = "UI/FileIntegrity/FailedMessage/Gog",
            UIFileIntegrityFailedMessageGeneric = "UI/FileIntegrity/FailedMessage/Generic",
            UIFileIntegrityFailedLinkGog = "UI/FileIntegrity/Link/Gog",

            UIShadersPreloadingProgress = "UI/ShadersPreloading/Progress",

            UIStatFaster = "UI/StatFaster",
            UIStatSlower = "UI/StatSlower",
            UIStatNormal = "UI/StatNormal",
            
            StatsUILeftTitle = "TitleLeft/StatsUI",
            QuestLogUILeftTitle = "TitleLeft/QuestLogUI",
            QuestTypeBase = "UI/QuestType",
            QuestName = "UI/QuestName",
            InventoryUITitle = "CharacterSheets/InventoryTittle",
            InventoryStatistics = "CharacterSheets/InventoryStatistics",
            ItemsLootTitle = "TitleRight/ItemsLoot",

            CharacterCreationTitle = "HeroCreator/CharacterCreationTitle",
            CharacterCreationEnterNamePlaceholder = "HeroCreator/EnterName",
            DefaultEventRewardTitle = "Events/RewardTitle",
            
            // --- Lock Attachment
            LockKeyRequired0 = "Lock/KeyRequired0",
            // LockKeyRequired1 = "Lock/KeyRequired1",
            // LockKeyRequired2 = "Lock/KeyRequired2",
            // LockKeyRequired3 = "Lock/KeyRequired3",
            // LockKeyRequired4 = "Lock/KeyRequired4",
            // LockKeyRequired5 = "Lock/KeyRequired5",
            // LockKeyRequired6 = "Lock/KeyRequired6",
            // LockKeyRequired7 = "Lock/KeyRequired7",
            // LockKeyRequired8 = "Lock/KeyRequired8",
            // LockKeyRequired9 = "Lock/KeyRequired9",
            
            LockSigilRequired0 = "Lock/SigilRequired0",
            // LockSigilRequired1 = "Lock/SigilRequired1",
            // LockSigilRequired2 = "Lock/SigilRequired2",
            // LockSigilRequired3 = "Lock/SigilRequired3",
            // LockSigilRequired4 = "Lock/SigilRequired4",
            // LockSigilRequired5 = "Lock/SigilRequired5",
            // LockSigilRequired6 = "Lock/SigilRequired6",
            // LockSigilRequired7 = "Lock/SigilRequired7",
            // LockSigilRequired8 = "Lock/SigilRequired8",
            // LockSigilRequired9 = "Lock/SigilRequired9",
            
            LockClosed0 = "Lock/Closed0",
            // LockClosed1 = "Lock/Closed1",
            // LockClosed2 = "Lock/Closed2",
            // LockClosed3 = "Lock/Closed3",
            // LockClosed4 = "Lock/Closed4",
            // LockClosed5 = "Lock/Closed5",
            // LockClosed6 = "Lock/Closed6",
            // LockClosed7 = "Lock/Closed7",
            // LockClosed8 = "Lock/Closed8",
            // LockClosed9 = "Lock/Closed9",
            
            LockNeutral0 = "Lock/Neutral0",
            // LockNeutral1 = "Lock/Neutral1",
            // LockNeutral2 = "Lock/Neutral2",
            
            LockCantPass0 = "Lock/CantPass0",
            // LockCantPass1 = "Lock/CantPass1",
            // LockCantPass2 = "Lock/CantPass2",
            // LockCantPass3 = "Lock/CantPass3",
            // LockCantPass4 = "Lock/CantPass4",
            // LockCantPass5 = "Lock/CantPass5",
            // LockCantPass6 = "Lock/CantPass6",
            // LockCantPass7 = "Lock/CantPass7",
            // LockCantPass8 = "Lock/CantPass8",
            // LockCantPass9 = "Lock/CantPass9",
            
            // --- Empty Content Info
            EmptyBagInfo = "EmptyContent/BagInfo",
            EmptyBagDesc = "EmptyContent/BagDesc",
            EmptyNoItems = "EmptyContent/NoItems",
            
            EmptyShopBuyBackDesc = "EmptyContent/ShopBuyBackDesc",
            EmptyShopSellInfo = "EmptyContent/ShopSellInfo",
            EmptyShopSellDesc = "EmptyContent/ShopSellDesc",
            EmptyShopSellFromStashDesc = "EmptyContent/ShopSellFromStash",
            EmptyShopBuyInfo = "EmptyContent/ShopBuyInfo",
            EmptyShopBuyDesc = "EmptyContent/ShopBuyDesc",
            
            EmptyCraftingNoItems = "EmptyContent/CraftingNoItems",
            EmptyCraftingGatherMaterials = "EmptyContent/GatherMaterials",
            EmptyCraftingNoIngredients = "EmptyContent/CraftingNoIngredients",
            EmptyCraftingGatherMaterialsDesc = "EmptyContent/GatherMaterialsDesc",
            EmptyCookingGatherMaterials = "EmptyContent/CookingGatherMaterials",
            EmptyCookingGatherMaterialsDesc = "EmptyContent/CookingGatherMaterialsDesc",
            
            EmptyRelicsInfo = "EmptyContent/RelicsInfo",
            EmptyRelicsDesc = "EmptyContent/RelicsDesc",
            
            EmptyStorageInfo = "EmptyContent/StorageInfo",
            EmptyStorageDesc = "EmptyContent/StorageDesc",
            
            EmptyQuestLogInfo = "EmptyContent/QuestLogInfo",
            EmptyQuestLogDesc = "EmptyContent/QuestLogDesc",
            
            // --- Saving & Loading
            SaveGame = "Loading/SaveGame",
            LoadGame = "Loading/LoadGame",
            NewSave = "Loading/NewSave",
            QuickSave = "Loading/QuickSave",
            AutoSave = "Loading/AutoSave",
            Slot = "Loading/Slot",
            SlotNameLengthTooShort = "Loading/SlotNameLengthTooShort",
            SlotNameForbidden = "Loading/SlotNameForbidden",

            LoadingFailedSaveFile = "Loading/FailedSaveFile",
            SavingFailed = "Loading/SavingFailed",
            Saving = "Loading/Saving",

            LoadingHintFirst = "LoadingHints/First",
            LoadingHintSecond = "LoadingHints/Second",
            LoadingHintThird = "LoadingHints/Third",
            LoadingHintFourth = "LoadingHints/Fourth",
            LoadingHintFifth = "LoadingHints/Fifth",
            LoadingHintSixth = "LoadingHints/Sixth",
            LoadingHintSeventh = "LoadingHints/Seventh",
            LoadingHintEighth = "LoadingHints/Eighth",

            TimeBasedCooldown = "Cooldown/TimeBasedCooldown",
            OnlyOnceCooldown = "Cooldown/OnlyOnceCooldown",
            
            SubColorDefault = "SubColor/Default",
            SubColorPureWhite = "SubColor/PureWhite",
            SubColorYellow = "SubColor/Yellow",

            // --- Cloud Sync
            CloudSyncConflict = "CloudSync/Conflict",
            CloudSyncConflictTitle = "CloudSync/ConflictTitle",
            CloudSyncChooseLocal = "CloudSync/ChooseLocal",
            CloudSyncChooseCloud = "CloudSync/ChooseCloud",
            CloudSyncFileDateNA = "CloudSync/FileDateNA",

            // --- Bug Reporting
            BugReportingSend = "BugReporting/BugReportingSend",
            BugReportingFailed = "BugReporting/BugReportingFailed",

            // --- Game Progress
            ProgressDiscovered = "GameProgress/Discovered",
            ProgressDiscoveredAndSaved = "GameProgress/DiscoveredAndSaved",
            Cards = "GameProgress/Cards",
            VillageNPC = "GameProgress/VillageNPC",
            SavableNPC = "GameProgress/SavableNPC",
            RegularNPC = "GameProgress/RegularNPC",
            Items = "GameProgress/Items",
            Bosses = "GameProgress/Bosses",
            Enemies = "GameProgress/Enemies",
            Locations = "GameProgress/Locations",

            // --- Tutorials
            TutorialOpenInventory = "Tutorial/OpenInventory",
            TutorialLightAttack = "Tutorial/LightAttack",
            TutorialHeavyAttack = "Tutorial/HeavyAttack",
            TutorialBlock = "Tutorial/Block",
            TutorialHideWeapon = "Tutorial/HideWeapon",
            TutorialShowActiveObjective = "Tutorial/ShowActiveObjective",
            TutorialDash = "Tutorial/Dash",
            TutorialPush = "Tutorial/Push",
            TutorialQuickUseWheel = "Tutorial/QuickUseWheel",
            TutorialWyrdPower = "Tutorial/WyrdPower",
            TutorialCrouch = "Tutorial/Crouch",
            TutorialSprint = "Tutorial/Sprint",
            TutorialWalk = "Tutorial/Walk",
            TutorialLoadoutsTitle = "Tutorial/LoadoutsTitle",
            TutorialLoadoutsText = "Tutorial/LoadoutsText",
            TutorialAutoFillSlotsTitle = "Tutorial/AutoFillSlotsTitle",
            TutorialAutoFillSlotsText = "Tutorial/AutoFillSlotsText",
            TutorialCraftingTitle = "Tutorial/CraftingTitle",
            TutorialCraftingText = "Tutorial/CraftingText",
            TutorialPopupFireplaceLevelUpTitle = "Tutorial/Popup/FireplaceLevelUpTitle",
            TutorialPopupFireplaceLevelUp = "Tutorial/Popup/FireplaceLevelUp",
            
            // --- Tools Tutorials
            TutorialSpyglassUse = "Tutorial/SpyglassUse",
            TutorialSpyglassSetMarker = "Tutorial/SpyglassSetMarker",
            TutorialFishingRodUse = "Tutorial/FishingRodUse",
            TutorialSketchbookUse = "Tutorial/SketchbookUse",
            TutorialPickaxeUse = "Tutorial/PickaxeUse",
            TutorialShovelUse = "Tutorial/ShovelUse",
            
            // --- Character Creator
            CharacterCreatorTitle = "CharacterCreator/Title",
            CharacterCreatorGender = "CharacterCreator/Gender",
            CharacterCreatorMale = "CharacterCreator/Male",
            CharacterCreatorFemale = "CharacterCreator/Female",
            CharacterCreatorBodySize = "CharacterCreator/BodySize",
            CharacterCreatorAge = "CharacterCreator/Age",
            CharacterCreatorMusculature = "CharacterCreator/Musculature",
            CharacterCreatorBodyNormals = "CharacterCreator/BodyNormals",
            CharacterCreatorPresets = "CharacterCreator/Presets",
            CharacterCreatorHeadShapes = "CharacterCreator/HeadShapes",
            CharacterCreatorHairs = "CharacterCreator/Hairs",
            CharacterCreatorBeard = "CharacterCreator/Beard",
            CharacterCreatorSkinColor = "CharacterCreator/SkinColor",
            CharacterCreatorHairColor = "CharacterCreator/HairColor",
            CharacterCreatorBeardColor = "CharacterCreator/BeardColor",
            CharacterCreatorEyeColor = "CharacterCreator/EyeColor",
            CharacterCreatorEyebrows = "CharacterCreator/Eyebrows",
            CharacterCreatorName = "CharacterCreator/Name",
            CharacterCreatorWrite = "CharacterCreator/Write",
            CharacterCreatorApplyChanges = "CharacterCreator/ApplyChanges",
            CharacterCreatorEmptyName = "CharacterCreator/EmptyName",
            CharacterCreatorForbiddenName = "CharacterCreator/ForbiddenName",
            CharacterCreatorToggleSkipIntroAreaDescription = "CharacterCreator/ToggleSkipIntroAreaDescription",
            CharacterCreatorToggleSkipIntroArea = "CharacterCreator/ToggleSkipIntroArea",
            CharacterCreatorFaceTattoo = "CharacterCreator/FaceTattoo",
            CharacterCreatorBodyTattoo = "CharacterCreator/BodyTattoo",
            CharacterCreatorFaceDetails = "CharacterCreator/FaceDetails",

            CharacterCreatorGameplayPresets = "CharacterCreator/GameplayPresets",

            // --- Lockpicking
            PicklockCount = "Lockpicking/PicklockCount",
            BrokenLockInfo = "Lockpicking/BrokenLockInfo",
            RotateLock = "Lockpicking/RotateLock",

            // --- Housing
            HousingTitle = "Housing/Title",
            HousingRoomUnlock = "Housing/RoomUnlock",
            HousingRoomEdit = "Housing/RoomEdit",
            HousingFurnitureEdit = "Housing/FurnitureEdit",
            HousingFurnitureVariantCount = "Housing/FurnitureVariantCount",
            HousingFurnitureOwned = "Housing/FurnitureOwned",
            HousingFurnitureInUse = "Housing/FurnitureInUse",
            HousingFurnitureThatCanBePlacedHere = "Housing/FurnitureThatCanBePlacedHere",
            HousingUnlockedRoomsHeader = "Housing/UnlockedRoomsHeader",
            HousingLockedRoomsHeader = "Housing/LockedRoomsHeader",
            HousingFurnitureHeader = "Housing/FurnitureHeader",
            HousingFurnitureVariantsHeader = "Housing/FurnitureVariantsHeader",
            HousingBuy = "Housing/Buy",
            HousingBuySuccess = "Housing/BuySuccess",
            HousingDecorMode = "Housing/DecorMode",
            
            // --- Farming
            FarmingPlant = "Farming/Plant",
            FarmingHarvest = "Farming/Harvest",
            FarmingSizeSmall = "Farming/SizeSmall",
            FarmingSizeLarge = "Farming/SizeLarge",
            FarmingPlantStateReadyForPlanting = "Farming/PlantStateReadyForPlanting",
            FarmingPlantStateGrowing = "Farming/PlantStateGrowing",
            FarmingPlantStateFullyGrown = "Farming/PlantStateFullyGrown",
            FarmingPlantStateBlocked = "Farming/PlantStateBlocked",
            FarmingRequiredSpace = "Farming/RequiredSpace",
            FarmingGrowthTime = "Farming/GrowthTime",
            FarmingFlowerbed = "Farming/Flowerbed",
            
            // --- Fireplace
            FireplaceBoost = "Fireplace/Boost",
            FireplacePray = "Fireplace/Pray",
            FireplaceFailedPrayMessage = "Fireplace/FailedPrayMessage",
            FireplaceTalkWithForedweller = "Fireplace/TalkWithForedweller",
            FireplaceRestoreWyrdSkill = "Fireplace/RestoreWyrdSkill",
            FireplaceRecallPet = "Fireplace/RecallPet",
            
            CookDescription = "Fireplace/CookDescription",
            RestDescription = "Fireplace/RestDescription",
            LevelUpDescription = "Fireplace/LevelUpDescription",
            TalkWithForedwellerDescription = "Fireplace/TalkWithForedwellerDescription",
            BoostDescription = "Fireplace/BoostDescription",
            RestoreWyrdSkillDescription = "Fireplace/RestoreWyrdSkillDescription",
            RecallPetDescription = "Fireplace/RecallPetDescription",
            IdentifyDescription = "Fireplace/IdentifyDescription",
            FastTravelDescription = "Fireplace/FastTravelDescription",
            FireplaceAlchemyDescription = "Fireplace/AlchemyDescription",
            FireplaceHandcraftingDescription = "Fireplace/AlchemyDescription",
            SaveGameDescription = "Fireplace/SaveGameDescription",
            
            // --- Resting
            RestingUntil = "Resting/RestingTimeUntil",
            
            // --- Sneak indicator
            SneakIndicatorDetected = "SneakIndicator/Detected",
            
            // --- Tracker Display Pattern
            TrackerPatternCurByMax = "QuestTracker/DisplayPattern/CurByMax",
            TrackerPatternItemCurByMax = "QuestTracker/DisplayPattern/ItemCurByMax",
            TrackerPatternCur = "QuestTracker/DisplayPattern/Cur",
            
            // --- Quests
            QuestTypeMain = "QuestType/Main",
            QuestTypeSide = "QuestType/Side",
            QuestTypeMisc = "QuestType/Misc",
            
            // --- Warnings
            WyrdnessRestWarning = "Warning/WyrdnessRestWarning",
            
            // --- Photo Mode
            CharacterCamera = "PhotoMode/CharacterCamera",
            FreeCamera = "PhotoMode/FreeCamera",
            
            // --- OST
            PreviousNextTrack = "OST/PreviousNextTrack",
            
            // --- Artbook
            ArtOf = "Artbook/ArtOf"
            ;
    }
}
