namespace Awaken.TG.Main.Animations.FSM.Npc.Base {
    public enum NpcStateType : byte {
        None = 0,
        // --- General
        Idle = 1,
        Movement = 2,
        Parried = 3,
        StaggerEnter = 4,
        StaggerLoop = 5,
        StaggerExit = 6,
        StumbleOneStep = 7,
        StumbleThreeStep = 8,
        EquipWeapon = 9,
        EquipRangedWeapon = 10,
        StandUp = 11,
        Taunt = 12,
        Attract = 13,
        Rest = 14,
        DashBack = 15,
        // --- Combat
        ShortRange = 16,
        ShortRangeCombo = 17,
        MediumRange = 18,
        LongRange = 19,
        LongRangeRunning = 20,
        SpecialAttack = 21,
        RangedAttack = 22,
        MagicProjectile = 23,
        MagicAoE = 24,
        MagicRay = 25,
        MagicAura = 26,
        BlockStart = 27,
        BlockHold = 28,
        BlockImpact = 29,
        BlockMovement = 30,
        Wait = 31,
        GetHit = 32,
        PoiseBreakFront = 33,
        PoiseBreakBackRight = 34,
        PoiseBreakBack = 35,
        PoiseBreakBackLeft = 36,
        DodgeLeft = 38,
        DodgeRight = 39,
        DodgeBack = 40,
        // --- Item using
        UseItemMainHand = 42,
        UseItemOffHand = 43,
        Death = 44,
        ThrowItemMainHand = 45,
        ThrowItemOffHand = 46,
        // --- New
        UnequipWeapon = 47,
        LookAround = 48,
        DodgeAttack = 49,
        CombatIdle = 50,
        CombatMovement = 51,
        ShieldManMovement = 52,
        RotateRight90 = 53,
        RotateRight180 = 54,
        RotateLeft90 = 55,
        RotateLeft180 = 56,
        RotateRight45 = 57,
        RotateLeft45 = 58,
        Fear = 59,
        
        MagicLoopStart = 60,
        MagicLoopHold = 61,
        MagicLoopEnd = 62,
        
        ChargeEnter = 63,
        ChargeLoop = 64,
        ChargeExit = 65,
        ChargeInterrupt = 66,
        
        AttackGeneric0 = 70,
        AttackGeneric1 = 71,
        AttackGeneric2 = 72,
        AttackGeneric3 = 73,
        AttackGeneric4 = 74,
        AttackGeneric5 = 75,
        AttackGeneric6 = 76,
        AttackGeneric7 = 77,
        AttackGeneric8 = 78,
        AttackGeneric9 = 79,
        
        PreventDamageEnter = 80,
        PreventDamageLoop = 81,
        PreventDamageExit = 82,
        PreventDamageInterrupt = 83,
        
        WyrdConversionIn = 90,
        WyrdConversionOut = 91,
        
        DeflectProjectilePhysical = 100,
        DeflectProjectileMagic = 101,
        
        AlertStart = 110,
        AlertStartQuick = 111,
        AlertLookAround = 112,
        AlertLookAt = 113,
        AlertIdle = 114,
        AlertMovement = 115,
        AlertExit = 116,
        
        FearIdle = 118,
        FearMovement = 119,
        
        // --- General specials
        Spawn = 120,
        TurnMovement = 121,
        PhaseTransition = 122,
        EquipWeaponFromSitting = 123,
        EquipWeaponFromCrouching = 124,
        EquipWeaponFromLying = 125,
        DialogueIdle = 126,
        ShieldManTurnMovement = 127,
        PhaseTransitionAlternate = 128,
        
        // --- Customs
        CustomEnter = 199,
        CustomLoop = 200,
        CustomStoryLoop = 201,
        CustomStoryLoopTalking = 202,
        CustomExit = 203,
        CustomGesticulate = 204,
        CustomAction = 205,
        CustomDeath = 206,
        CustomEquipWeapon = 207,
        CustomEquipWeaponFromBack = 208,
        CustomFinisherDeath = 209,
    }
}