namespace Awaken.TG.Main.Tutorials {
    public enum SequenceKey {
        [UnityEngine.Scripting.Preserve] None = 0,
        [UnityEngine.Scripting.Preserve] OpenInventory = 1,
        [UnityEngine.Scripting.Preserve] LightAttack = 2,
        [UnityEngine.Scripting.Preserve] HeavyAttack = 3,
        [UnityEngine.Scripting.Preserve] Block = 4,
        [UnityEngine.Scripting.Preserve] HideWeapon = 5,
        [UnityEngine.Scripting.Preserve] Dash = 6,
        [UnityEngine.Scripting.Preserve] Pommel = 7,
        [UnityEngine.Scripting.Preserve] QuickUseWheel = 8,
        [UnityEngine.Scripting.Preserve] WyrdPower = 9,
        [UnityEngine.Scripting.Preserve] Crouch = 10,
        [UnityEngine.Scripting.Preserve] Sprint = 11,
        [UnityEngine.Scripting.Preserve] ShowActiveObjective = 12,
        [UnityEngine.Scripting.Preserve] Walk = 13,
        [UnityEngine.Scripting.Preserve] SetUpCamp = 14,
        [UnityEngine.Scripting.Preserve] FireplaceLevelUp = 15,
        [UnityEngine.Scripting.Preserve] Wyrdness = 19,
        [UnityEngine.Scripting.Preserve] EquipmentScreen = 21,
        [UnityEngine.Scripting.Preserve] ParryOnCombat = 22,
        [UnityEngine.Scripting.Preserve] SoulFragment1 = 23,
        [UnityEngine.Scripting.Preserve] SpyglassAcquire = 24,
        [UnityEngine.Scripting.Preserve] FishingRodAcquire = 25,
        [UnityEngine.Scripting.Preserve] SketchbookAcquire = 26,
        [UnityEngine.Scripting.Preserve] PickaxeAcquire = 27,
        [UnityEngine.Scripting.Preserve] ShovelAcquire = 28,
        [UnityEngine.Scripting.Preserve] HorseAcquire = 29,
        [UnityEngine.Scripting.Preserve] RedDeathSkillTreeUnlock = 30,
        [UnityEngine.Scripting.Preserve] FirstMemoryShardAcquire = 31,
        [UnityEngine.Scripting.Preserve] FirstWyrdWhisperAcquire = 32, 
        [UnityEngine.Scripting.Preserve] ParryOnTrigger = 33,
        [UnityEngine.Scripting.Preserve] HorseArmorDlc = 34,
        [UnityEngine.Scripting.Preserve] Fishing = 35
    }
}